### ISSUE TITLE
Regarding the MLCS plugin to make levels multi-select

### ISSUE THREAD

**Issue by ramchavan** [sourcesense/jira-multi-level-cascade-select#10]
Hi ,

I wanted to ckeck whether we can make a MLCS field levels multi select.

Like i wanted to select one option from first level and 2 options from second level.

Is it possible im MLCS field?

Thanks,
 Ram

**Comment by alessandrobenedetti** [comment]
Hi ramchavan,
this feature is not included in the concept of the plug-in ...
It would be necessary to develop a specific plugin ...
