### ISSUE TITLE
2nd tier select list shows all options of Tier 1 list

### ISSUE THREAD

**Issue by micahf** [sourcesense/jira-multi-level-cascade-select#11]
When I have the following setup in the custom fields:

Server:
- Database
- Web
- Memcache

Network:
- Routing
- Latency

When I go to edit the fields in an issue after I select Network the 2nd select box still has all the options for Server in it too,

**Comment by alessandrobenedetti** [comment]
Where did you find this issue?
Which version of jira and Plugin ?
I can't reproduce it ...

**Comment by micahf** [comment]
running jira 4.3.4 with plugin version 2.5-SNAPSHOT

I found the issue on my jira instance just setting this up normally

**Comment by alessandrobenedetti** [comment]
I hava done a lot of test , but I can't reproduce this Issue!
I can suggest to try my latest release and tell me if you can reproduce the issue!

**Comment by alessandrobenedetti** [comment]
The issue has been in solved in the last release :)
You can find it in the download section!
If you can reproduce the bug also with the new version, please contact me!
