### ISSUE TITLE
Drilling down from pie chart gadget produces filter that doesn't work

### ISSUE THREAD

**Issue by ghost** [sourcesense/jira-multi-level-cascade-select#12]
This issue exists in 2.4 version (On Jira 4.2).  to reproduce, do the following

1) Create a filter that includes the Multi level select field as a statistic
2) Click on a slice of pie
3) watch how the resulting Filter fails.

Examples below of failed filter and how to get the filter to work.
BROKEN SEARCH generated By the 'slice of pie':

project = MYPROJ AND issuetype = "Bug" AND created >= 2011-06-05 AND created <= 2011-06-07 AND project in (10011) AND issuetype in ("10") and cf[10050] = "Engineering / Tech - Safety Equipment"

WORKING (manually changed query):
project = MYPROJ AND issuetype = "Bug" AND created >= 2011-06-05 AND created <= 2011-06-07 AND project in (10011) AND issuetype in ("10") AND cf[10050] = "Engineering / Tech" and cf[10050] = "Safety Equipment"

**Comment by alessandrobenedetti** [comment]
The issue has been solved with my last commit!

**Comment by ghost** [comment]
Thank you Allesandro I will test that out and update to let you know.

Apologies for not replying sooner.

Regards

Rob
