### ISSUE TITLE
Incompatibility with JIRA 4.2.x - Part 1

### ISSUE THREAD

**Issue by alweiss** [sourcesense/jira-multi-level-cascade-select#2]
I did some additional test with different constellations:

 JIRA: 4.2
 Plug-In: Multi Level 2.1
 Bug: "fully" present: No search possible due to impossible expanding (de-collapsing) of searchfield sections in simple search mode (all sections are closed) and no drop downs of main navigation possible.

 JIRA: 4.1.2
 Plug-In: Multi Level 2.1
 Bug: "partitially" present: The collapsing/expanding of the search mask sections  below (e.g. to open/close the custom field searcher section in simple search mode) works in 4.1.2 fine. But the issue to open the main navigation dropdowns (ajax) for  instance for "Dashboars", "Projecs" and "Issues" still not works within the creation and edit mask.

 Since our production system is JIRA 4.2 we are still in trouble ;-)

 And indeed I remember that Atlassian changed the html layout of the searchmask from table to <div>s during the change from 4.1.x to version 4.2. I guess this is the reason why the issue is inherent (back again).

 With best regards,

 Alexander

> -----Original Message-----
> From: Marco Abis [mailto:m.abis@sourcesense.com]
> Sent: Dienstag, 18. Januar 2011 14:09
> To: Alexander Weiss
> Subject: Re: Test Feedback II: 'Multi level cascade select' <-- feedback
> to bundle 2.1
> 
> Hi Alexander,
> 
>    thanks as usual for the feedback. We did test this functionality
> with all the browsers and didn't find any issues. After you email this
> is what we've tried:
> 
> Ho provato di nuovo:
> 
> Jira : 4.1.2
> Plug-in : Multi Level 2.0 (the  previous version)
> Bug: present
> 
> Then on the same Jira instance we've installed the latest plug-in
> (version 2.1) and the bugs disappears. While we keep investigating could
> you please check that the installation of v 2.1 was done correctly and
> are no v 2.0 leftovers?
> 
> Thanks again!
> ## 
> 
> Marco Abis

**Comment by mabis** [comment]
Thanks Alex for using the issue tracker. Try with the latest snapshot (2.2, now available also clicking on Download): https://github.com/downloads/sourcesense/jira-multi-level-cascade-select/cascadingselect-2.2-SNAPSHOT-bundle.zip

**Comment by alweiss** [comment]
Hi Marco,

with this snapshot I get a lot of logged errors like following:

ERROR mgm.weiss 1049x332x1 1yg5jzt 192.168.2.81 /secure/ViewUserIssueColumns!default.jspa [com.atlassian.velocity.DefaultVelocityManager] MethodInvocationException occurred getting message body from Velocity: java.lang.ClassCastException: com.atlassian.jira.issue.DocumentIssueImpl cannot be cast to com.atlassian.jira.issue.MutableIssue
java.lang.ClassCastException: com.atlassian.jira.issue.DocumentIssueImpl cannot be cast to com.atlassian.jira.issue.MutableIssue
    at com.sourcesense.jira.customfield.type.MultiLevelCascadingSelectCFType.getVelocityParameters(MultiLevelCascadingSelectCFType.java:223)
    at com.atlassian.jira.issue.customfields.CustomFieldUtils.buildParams(CustomFieldUtils.java:429) 
.....
