### ISSUE TITLE
Incompatibility with JIRA 4.2.x - Part 2

### ISSUE THREAD

**Issue by alweiss** [sourcesense/jira-multi-level-cascade-select#3]
Hi,

Just found a further issue within JIRA 4.2. The new 'pop-up' dialogs
(what is that? See first bullet within atlassian release notes for JIRA
4.2: http://confluence.atlassian.com/x/tgBrDQ) doesn't work any more
with MLCS fields. So there is no possility to make a workflow transition
etc.

Cheers,

Alexander

**Comment by mabis** [comment]
see comment to issue 2: https://github.com/sourcesense/jira-multi-level-cascade-select/issues/closed/#issue/2
