### ISSUE TITLE
Not yet compatible with JIRA 4.3

### ISSUE THREAD

**Issue by dietergreiner** [sourcesense/jira-multi-level-cascade-select#7]
snapshot 2.3 still gives me runtime errors in the *FieldValidator classes since jqlSelectOptionsUtil.getOptions is called with the old OSUser object. 

and ... thank's guys for that great work!

**Comment by dietergreiner** [comment]
Something else i noted in JIRA 4.4 EAP3:
When i put a Multi Level Cascade Select field on my create/edit screen due date, component and version fields cannot be edited anymore. Is this something you can reproduce? I had a closer look at the component field and noticed that the class attribute is not changed to multi-select. 
Do you have any idea why the mlcsf field has an impact on other fields?

**Comment by mabis** [comment]
Thanks for the feedback! We won't be looking into Jira 4.4 until everything for 4.3 is resolved :-)

**Comment by dietergreiner** [comment]
Never mind ... today i got it working under JIRA 4.4 :) I did some simple changes:
- remove all script includes except the one for multilevelcascadingUtil.js from multi-level-cascading-select-edit.vm  since jquery is provided in a newer version by JIRA 4.4 and i also could not see where cascadingutils.js is used
- replace $ by jQuery in multilevelcascadingUtil.js since jQuery is the object already provided by JIRA 4.4
