### ISSUE TITLE
erroneous level order in gadgets (e.g. two-dimensional and filter-statistic)

### ISSUE THREAD

**Issue by alweiss** [sourcesense/jira-multi-level-cascade-select#8]
_The issue is related to version 2.5 SNAPSHOT_

When displaying a filter result within a _2-dimensional_ or _filter statistic_ the order of displayed cascading multilevel options are in a wrong order. In my case following example illustrates the issue:

`Level 1 --- Level 3 --------- Level 2
"ELSTER - Sonstige (K) - ElsterFachmethodik" is displayed but wrong!`

the correct order would be:

"ELSTER - ElsterFachmethodik - Sonstige (K)" 

Level 1 is correct, but level 2 and 3 are replaced.

When clicking on one of the gadget links the search result end up with an empty result, because the search query will be generated faulty.

My assumption is that the indexing is going wrong because changing (correcting) manually the generated query will also result in an empty list.
Her is an example of a wrong generated gadget filter query:
`project = KIM AND issuetype = Incident AND resolution = Unresolved AND project in (12310470) AND issuetype in ("41") AND cf[12310521] = "ELSTER - Sonstige (K) - ElsterFachmethodik"`

The same behaviour occures in the pie chart and within the extended  search mode of JIRA when building queries like above.
'''

**Comment by alessandrobenedetti** [comment]
Fixed in the latest release :)
